trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  vmHost: '20.238.104.200'

stages:
  - stage: Deploy
    jobs:
      - job: DeployReactApp
        steps:
          - download: current
            artifact: react-app-build

          - script: |
              mkdir -p ansible/files
              cp -r $(Pipeline.Workspace)/react-app-build/* ansible/files/
            displayName: 'Prepare Build for Ansible'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'ansible/files'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/ansible/files'
            displayName: 'Copy build files locally'

          - task: CmdLine@2
            inputs:
              script: |
                cd ansible
                ansible-playbook -i inventory.ini react-deploy.yaml --extra-vars "target_host=$(vmHost)"
            displayName: 'Run Ansible Playbook'
